/**
 * @handled-ai/design-system
 * UI components and utilities (shadcn-style, New York)
 */

export { cn } from "./lib/utils"
export { useIsMobile } from "./hooks/use-mobile"

export * from "./registry/new-york/ui/activity-detail"
export * from "./registry/new-york/ui/activity-log"
export * from "./registry/new-york/ui/avatar"
export * from "./registry/new-york/ui/badge"
export * from "./registry/new-york/ui/bar-chart-component"
export * from "./registry/new-york/ui/button"
export * from "./registry/new-york/ui/card"
export * from "./registry/new-york/ui/chart"
export * from "./registry/new-york/ui/chart-tooltip"
export * from "./registry/new-york/ui/contact-list"
export * from "./registry/new-york/ui/dashboard-cards"
export * from "./registry/new-york/ui/data-table"
export * from "./registry/new-york/ui/data-table-display"
export * from "./registry/new-york/ui/data-table-filter"
export * from "./registry/new-york/ui/data-table-quick-views"
export * from "./registry/new-york/ui/data-table-toolbar"
export * from "./registry/new-york/ui/detail-view"
export * from "./registry/new-york/ui/dialog"
export * from "./registry/new-york/ui/donut-chart"
export * from "./registry/new-york/ui/dropdown-menu"
export * from "./registry/new-york/ui/entity-panel"
export * from "./registry/new-york/ui/inbox-row"
export * from "./registry/new-york/ui/inbox-toolbar"
export * from "./registry/new-york/ui/input"
export * from "./registry/new-york/ui/item-list"
export * from "./registry/new-york/ui/item-list-display"
export * from "./registry/new-york/ui/item-list-filter"
export * from "./registry/new-york/ui/item-list-toolbar"
export * from "./registry/new-york/ui/label"
export * from "./registry/new-york/ui/metric-card"
export * from "./registry/new-york/ui/performance-metrics-table"
export * from "./registry/new-york/ui/pipeline-overview"
export * from "./registry/new-york/ui/preview-list"
export * from "./registry/new-york/ui/progress"
export * from "./registry/new-york/ui/quick-action-chat-area"
export {
  QuickActionModal,
  type QuickActionTaskDraft,
  type QuickActionTemplate,
} from "./registry/new-york/ui/quick-action-modal"
export * from "./registry/new-york/ui/quick-action-sidebar-nav"
export * from "./registry/new-york/ui/recommended-actions-section"
export * from "./registry/new-york/ui/report-card"
export * from "./registry/new-york/ui/sankey-chart"
export * from "./registry/new-york/ui/score-analysis-modal"
export * from "./registry/new-york/ui/score-breakdown"
export * from "./registry/new-york/ui/score-feedback"
export * from "./registry/new-york/ui/score-ring"
export * from "./registry/new-york/ui/scroll-area"
export * from "./registry/new-york/ui/select"
export * from "./registry/new-york/ui/separator"
export * from "./registry/new-york/ui/sheet"
export * from "./registry/new-york/ui/sidebar"
export * from "./registry/new-york/ui/signal-feedback-inline"
export * from "./registry/new-york/ui/skeleton"
export * from "./registry/new-york/ui/styled-bar-list"
export * from "./registry/new-york/ui/suggested-actions"
export * from "./registry/new-york/ui/table"
export * from "./registry/new-york/ui/tabs"
export * from "./registry/new-york/ui/textarea"
export * from "./registry/new-york/ui/timeline-activity"
export * from "./registry/new-york/ui/tooltip"
export * from "./registry/new-york/ui/top-line-metrics"
export * from "./registry/new-york/ui/trend-area-chart"
export * from "./registry/new-york/ui/view-mode-toggle"
export * from "./registry/new-york/ui/volume-analysis-chart"

// Prototype template system
export * from "./registry/new-york/ui/prototype-config"
export * from "./registry/new-york/ui/prototype-shell"
export * from "./registry/new-york/ui/prototype-inbox-view"
export * from "./registry/new-york/ui/prototype-insights-view"
export * from "./registry/new-york/ui/prototype-accounts-view"
export * from "./registry/new-york/ui/prototype-work-queue-view"

// Recruiting patterns
export * from "./registry/new-york/ui/message"
export * from "./registry/new-york/ui/status-badge"
export * from "./registry/new-york/ui/simple-data-table"
export * from "./registry/new-york/ui/agent-orb"
export * from "./registry/new-york/ui/agent-popover"
export * from "./registry/new-york/ui/agent-widget"
