import { defineConfig } from "tsup"

export default defineConfig({
  entry: ["index.ts"],
  format: ["esm"],
  dts: true,
  tsconfig: "tsconfig.build.json",
  outDir: "dist",
  clean: true,
  sourcemap: true,
  treeshake: true,
  minify: false,
  splitting: false,
  bundle: true,
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "@radix-ui/react-slot",
    "@radix-ui/react-label",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "date-fns",
    "recharts",
    "zod",
    "radix-ui",
    "@tanstack/react-table",
    "@nivo/sankey",
    "@nivo/core",
    "three",
    "@react-three/fiber",
    "@react-three/drei",
  ],
})
